WIP: [RFE] Allow multiple groups creation
freeipa/ansible-freeipa pull request #1001
Opened 2022-12-04 21:01 UTC by dkarpele

Adding an option to create multiple groups in one go. 
Adding tests (present/absent)

Signed-off-by: Denis Karpelevich <dkarpele@redhat.com>

2022-12-26 13:53 UTC, rjeffman commented on plugins/modules/ipagroup.py
> +def check_parameters(  # pylint: disable=unused-argument
Other than `module`, `state` and `action`, the other parameters are not needed.

2022-12-26 14:17 UTC, rjeffman commented on tests/group/test_groups_absent.yml
> +      state: absent
Please, clean up file `groups.json` after test completion.

2022-12-26 14:17 UTC, rjeffman commented on tests/group/test_groups_present.yml
> +      groups: "{{ group_list }}"
Please, clean up file `groups.json` after test completion.

2022-12-26 14:17 UTC, rjeffman commented on tests/group/test_groups_present_slice.yml
> +    loop: "{{ range(0,group_list | length, slice_size) | list }}"
Please, clean up file `groups.json` after test completion.

2022-12-26 14:19 UTC, rjeffman requested changes
@dkarpele thank you for the PR.

It looks good, but please check the suggestions.

2022-12-26 21:50 UTC, rjeffman approved these changes
LGTM.

2023-01-11 11:09 UTC, varunmylaraiah approved these changes
LGTM

2023-01-11 12:21 UTC, rjeffman commented
@dkarpele, please squash commits into one using the first commit message.

2023-01-24 08:24 UTC, varunmylaraiah commented
@dkarpele 
How can we add a group with a non-posix or external type using JSON? If it is not currently implemented, please implement it."

2023-01-26 20:34 UTC, dkarpele commented
> @dkarpele How can we add a group with a non-posix or external type using JSON? If it is not currently implemented, please implement it."

Great catch @varunmylaraiah! This problem is not related to JSON and there is no issue with external type. The failing case is with nonposix. The group `group_nonposix` will be created as a `posixgroup`:
```
 - name: Add nonposix groups
    ipagroup:
      ipaadmin_password: SomeADMINpassword
      groups:
      - name: group_nonposix
        nonposix: yes
```
I'll investigate it.

2023-02-02 21:04 UTC, dkarpele commented
Hi @rjeffman and @varunmylaraiah, could you please re-review the PR? I added a patch for bug found by Varun and test for the nonposix/external case.

2023-02-08 12:42 UTC, rjeffman requested changes
@dkarpele please check and fix the warnings raised by action "Verify ansible-lint". (It seems they are easy to spot in "Files changed".)

2023-02-08 16:12 UTC, dkarpele commented
@rjeffman fixed

2023-02-10 15:14 UTC, rjeffman requested changes
@dkarpele also, make the PR a single commit (or at most two, one for the plugin, one for the tests, but one commit is good enough for this one).

2023-02-11 19:48 UTC, rjeffman approved these changes
lgtm

2023-02-13 12:39 UTC, varunmylaraiah commented
LGTM.

2023-02-15 15:21 UTC, t-woerner commented
Please add examples for multi group use to the readme and also to the EXAMPLES section in the plugin.

2023-02-22 15:36 UTC, varunmylaraiah requested changes
This PR has an issue when adding external group with members. 

```
[root@ansible ~]# cat external_with_members.json
{
    "multiplegroups": [
      {
        "name": "066externalgroup",
        "description": "test add external groups with members",
        "external": "yes",
        "user": "gmm_user01",
        "group": ["gmm_group01", "gmm_group02"]
      }
    ]
  }
  
```
  
```
  
  [root@ansible ~]# cat group_module2.yml
---
- name: Playbook to ensure add multiple groups with members using json file.
  hosts: ipaserver
  become: true

  tasks:
  - name: groups add using json file
    include_vars:
      file: external_with_members.json  # noqa missing-import

  - name: Groups
    ipagroup:
      ipaadmin_password: <xxxxxxxxxxx>
      "groups": "{{ multiplegroups }}"
      
```
 
 ```

 PLAYBOOK: group_module2.yml ***********************************************************************************
1 plays in group_module2.yml

PLAY [Playbook to ensure add multiple groups with members using json file.] ***********************************

TASK [Gathering Facts] ****************************************************************************************
task path: /root/group_module2.yml:2
ok: [master.ipadomain.test]
META: ran handlers

TASK [groups add using json file] *****************************************************************************
task path: /root/group_module2.yml:7
ok: [master.ipadomain.test] => {"ansible_facts": {"multiplegroups": [{"description": "test add multiple external groups", "external": "yes", "group": ["gmm_group01", "gmm_group02"], "name": "066externalgroup", "user": "gmm_user01"}]}, "ansible_included_var_files": ["/root/external_with_members.json"], "changed": false}

TASK [Groups] *************************************************************************************************
task path: /root/group_module2.yml:11
fatal: [master.ipadomain.test]: FAILED! => {"changed": false, "msg": "group_add_member: 066externalgroup: Cannot perform external member validation without Samba 4 support installed. Make sure you have installed server-trust-ad sub-package of IPA on the server"}

PLAY RECAP ****************************************************************************************************
master.ipadomain.test      : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

2023-02-22 15:38 UTC, varunmylaraiah commented
or

```
[root@ansible ~]# cat external_group_with_members.yaml
---
- name: Playbook to ensure a external group is present with members
  hosts: ipaserver
  become: true

  tasks:
  # Create group
  - ipagroup:
      ipaadmin_password: <xxxxxxx>
      name: testexternal
      external: yes
  - ipagroup:
      ipaadmin_password:  <xxxxxxx>
      name: testexternal
      action: member
      user: gmm_user01
      
      
 PLAYBOOK: external_group_with_members.yaml ********************************************************************
1 plays in external_group_with_members.yaml

PLAY [Playbook to ensure a external group is present with members] ********************************************

TASK [Gathering Facts] ****************************************************************************************
task path: /root/external_group_with_members.yaml:2
ok: [master.ipadomain.test]
META: ran handlers

TASK [ipagroup] ***********************************************************************************************
task path: /root/external_group_with_members.yaml:8
ok: [master.ipadomain.test] => {"changed": false}

TASK [ipagroup] ***********************************************************************************************
task path: /root/external_group_with_members.yaml:12
fatal: [master.ipadomain.test]: FAILED! => {"changed": false, "msg": "group_add_member: testexternal: Cannot perform external member validation without Samba 4 support installed. Make sure you have installed server-trust-ad sub-package of IPA on the server"}

PLAY RECAP ****************************************************************************************************
master.ipadomain.test      : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

2023-02-22 20:12 UTC, dkarpele commented
Hi @varunmylaraiah,
1. I think this is not a bug. If you check any test with external members, for example `test_group_external_members.yml` there is a condition: `when: trust_test_is_supported | default(false)`. Please recheck your test with this condtion.
2. The second scenario you mention doesn't have `groups` at all. So, even, if it's a bug - it's not related to current PR.

2023-02-23 03:39 UTC, varunmylaraiah commented
Hello @dkarpele @t-woerner,
It appears that there is a problem with the module. After trying the same scenario on the master branch, I observed the same error. However, the group and its members were added. Additionally, I tested it on the CLI but I did not see any error.

[root@master ~]# ipa group-show testexternal
ipa: ERROR: testexternal: group not found

```
---
- name: Playbook to ensure a external group is present with members
  hosts: ipaserver
  become: true

  tasks:
  # Create group
  - ipagroup:
      ipaadmin_password: <xxxxxxx>
      name: testexternal
      external: yes
  - ipagroup:
      ipaadmin_password:  <xxxxxxx>
      name: testexternal
      action: member
      user: gmm_user01

PLAYBOOK: external_group_with_members.yaml ********************************************************************
1 plays in external_group_with_members.yaml

PLAY [Playbook to ensure a external group is present with members] ********************************************

TASK [Gathering Facts] ****************************************************************************************
task path: /root/external_group_with_members.yaml:2
ok: [master.ipadomain.test]
META: ran handlers

TASK [ipagroup] ***********************************************************************************************
task path: /root/external_group_with_members.yaml:8
changed: [master.ipadomain.test] => {"changed": true}

TASK [ipagroup] ***********************************************************************************************
task path: /root/external_group_with_members.yaml:12
fatal: [master.ipadomain.test]: FAILED! => {"changed": false, "msg": "group_add_member: testexternal: Cannot perform external member validation without Samba 4 support installed. Make sure you have installed server-trust-ad sub-package of IPA on the server"}

PLAY RECAP ****************************************************************************************************
master.ipadomain.test      : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0



**Group "testexternal" and its members "gmm_user01" were added**
[root@master ~]# ipa group-show testexternal --all
  dn: cn=testexternal,cn=groups,cn=accounts,dc=ipadomain,dc=test
  Group name: testexternal
  Member users: gmm_user01
  ipauniqueid: 3e42bd6a-b328-11ed-bc82-fa163e349009
  objectclass: top, groupofnames, nestedgroup, ipausergroup, ipaobject,
               ipaexternalgroup

```
**CLI execution:**

```
[root@master ~]# ipa group-show testexternal
ipa: ERROR: testexternal: group not found

[root@master ~]# ipa group-add testexternal --external
--------------------------
Added group "testexternal"
--------------------------
  Group name: testexternal

[root@master ~]# ipa group-add-member testexternal --users=gmm_user01
  Group name: testexternal
  Member users: gmm_user01
-------------------------
Number of members added 1
-------------------------

[root@master ~]# ipa group-show testexternal --all
  dn: cn=testexternal,cn=groups,cn=accounts,dc=ipadomain,dc=test
  Group name: testexternal
  Member users: gmm_user01
  ipauniqueid: 26c22e2a-b32b-11ed-8139-fa163e349009
  objectclass: top, groupofnames, nestedgroup, ipausergroup, ipaobject,
               ipaexternalgroup
```

2023-02-23 10:16 UTC, dkarpele commented
Thanks @varunmylaraiah. As you were able to reproduce it in master and without `groups` argument, could you open a separate issue for this problem? To avoid confusion, I don't think we should discuss it here.

2023-02-26 15:05 UTC, varunmylaraiah approved these changes

2023-02-27 08:47 UTC, varunmylaraiah commented
Hi @dkarpele 
Please have a look below scenarios.
In the first scenario, I attempted to add three groups using JSON (a non-posix group, a posix group, and another non-posix group). While trying to add the second non-posix group, I encountered the error message: 
`"FAILED! => {"changed": false, "msg": "group_add: 07nonposixgroup: missing attribute "gidNumber" required by object class "posixGroup""}"`

In the second scenario, I successfully added the same non-posix group (07nonposixgroup). 

Please have a look.


First scenario.
```
# cat group_module.yml
---
- name: Playbook to ensure add multiple groups with members using json file.
  hosts: ipaserver
  become: true

  tasks:
  - name: groups add using json file
    include_vars:
      file: group_add_multiple_groups.json  # noqa missing-import

  - name: Groups
    ipagroup:
      ipaadmin_password: <xxxxxxxxxxxx>
      "groups": "{{ multiplegroups }}"
      

# cat group_add_multiple_groups.json
{
  "multiplegroups": [
    {
      "name": "06nonposixgroup",
      "description": "test add nonposix group with members",
      "nonposix": "yes",
      "group": ["gmm_group01", "gmm_group02"]
    },
    {
      "name": "06posixgroup",
      "description": "test add posix group with members",
      "user": ["gmm_user01", "gmm_user02"]
    },
    {
      "name": "07nonposixgroup",
      "description": "test add nonposix group with member",
      "nonposix": "yes",
      "user": ["gmm_user01"],
      "group": ["gmm_group01", "gmm_group02"]
    }
  ]
  
  
PLAYBOOK: group_module.yml **********************************************************************************************************************************************************************************************************
1 plays in group_module.yml

PLAY [Playbook to ensure add multiple groups with members using json file.] *********************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************************************************
task path: /root/group_module.yml:2
ok: [master.ipadomain.test]
META: ran handlers

TASK [groups add using json file] ***************************************************************************************************************************************************************************************************
task path: /root/group_module.yml:7
ok: [master.ipadomain.test] => {"ansible_facts": {"multiplegroups": [{"description": "test add nonposix group with members", "group": ["gmm_group01", "gmm_group02"], "name": "06nonposixgroup", "nonposix": "yes"}, {"description": "test add posix group with members", "name": "06posixgroup", "user": ["gmm_user01", "gmm_user02"]}, {"description": "test add nonposix group with member", "group": ["gmm_group01", "gmm_group02"], "name": "07nonposixgroup", "nonposix": "yes", "user": ["gmm_user01"]}]}, "ansible_included_var_files": ["/root/group_add_multiple_groups.json"], "changed": false}

TASK [Groups] ***********************************************************************************************************************************************************************************************************************
task path: /root/group_module.yml:11
fatal: [master.ipadomain.test]: FAILED! => {"changed": false, "msg": "group_add: 07nonposixgroup: missing attribute \"gidNumber\" required by object class \"posixGroup\""}
```

Second scenario
```
[root@ansible ~]# cat group_module.yml
---
- name: Playbook to ensure add multiple groups with members using json file.
  hosts: ipaserver
  become: true

  tasks:
  - name: groups add using json file
    include_vars:
      file: group_add_multiple_groups.json  # noqa missing-import

  - name: Groups
    ipagroup:
      ipaadmin_password: <xxxxxxxxxxxxx>
      "groups": "{{ multiplegroups }}"
 
 
[root@ansible ~]# cat group_add_multiple_groups.json
{
  "multiplegroups": [
    {
      "name": "07nonposixgroup",
      "description": "test add nonposix group with member",
      "nonposix": "yes",
      "user": ["gmm_user01"],
      "group": ["gmm_group01", "gmm_group02"]
    }
  ]
}


PLAYBOOK: group_module.yml *******************************************************************************************************************************************************************************
1 plays in group_module.yml

PLAY [Playbook to ensure add multiple groups with members using json file.] ******************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************
task path: /root/group_module.yml:2
ok: [master.ipadomain.test]
META: ran handlers

TASK [groups add using json file] ************************************************************************************************************************************************************************
task path: /root/group_module.yml:7
ok: [master.ipadomain.test] => {"ansible_facts": {"multiplegroups": [{"description": "test add nonposix group with member", "group": ["gmm_group01", "gmm_group02"], "name": "07nonposixgroup", "nonposix": "yes", "user": ["gmm_user01"]}]}, "ansible_included_var_files": ["/root/group_add_multiple_groups.json"], "changed": false}

TASK [Groups] ********************************************************************************************************************************************************************************************
task path: /root/group_module.yml:11
changed: [master.ipadomain.test] => {"changed": true}
META: ran handlers
META: ran handlers

PLAY RECAP ***********************************************************************************************************************************************************************************************
master.ipadomain.test      : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0


[root@master ~]# ipa group-show --all 07nonposixgroup
  dn: cn=07nonposixgroup,cn=groups,cn=accounts,dc=ipadomain,dc=test
  Group name: 07nonposixgroup
  Description: test add nonposix group with member
  Member users: gmm_user01
  Member groups: gmm_group02, gmm_group01
  ipauniqueid: efb569d8-b677-11ed-8bf9-fa163e349009
  objectclass: top, groupofnames, nestedgroup, ipausergroup, ipaobject


```

2023-02-27 12:46 UTC, dkarpele commented
Thanks @varunmylaraiah , i was able to reproduce the issue. The failing case is:
```
      groups:
      - name: 06posixgroup
      - name: 07nonposixgroup
        nonposix: yes
```
but not vice versa:
```
      groups:
      - name: 07nonposixgroup
        nonposix: yes
      - name: 06posixgroup
```

2023-03-06 16:03 UTC, t-woerner commented
I am able to reproduce the issue. Strange is that the issue does not appear using the client context. This really seems to be an IPA issue.

2023-03-13 14:01 UTC, rjeffman commented
The performance gain from using batch mode seems to overcome the performance loss from using the client context.

Can we force the client-context for batch mode only? I mean... possible, it is, but do we want it to be done in a way that the default context will be different for batch/non-batch cases?

2023-03-30 12:36 UTC, t-woerner commented
Please add this to the README:

Note
-------
Ensuring (adding) several groups with mixed types external, nonposix and posix require to have a fix in IPA. The module implements a work-a-round to automatically switch to the client context if the fix is not applied to IPA and if more than one group is to be ensured with the groups parameter. If `ipaapi_context` is forced to be `server`, the module will fail in this case.

2023-03-30 19:23 UTC, dkarpele commented
🙏

2023-03-30 19:49 UTC, rjeffman commented on README-group.md
> +Ensuring (adding) several groups with mixed types `external`, `nonposix` and `posix` require to have a fix in IPA. The module implements a work-a-round to automatically switch to the `client` context
I suggest a few changes to this text:

> Ensuring presence (adding) of several groups with mixed types (`external`, `nonposix` and `posix`) requires a fix in FreeIPA. The module implements a workaround to automatically use `client` context if the fix is not present in the target node FreeIPA and if more than one group is provided to the task using the `groups` parameter. If `ipaapi_context` is forced to be `server`, the module will fail in this case.

2023-03-30 19:50 UTC, rjeffman commented on README-group.md
> +    ...
The ellipsis is not needed here. I suggest to remove it, along with the previous comma ",".

2023-03-30 19:51 UTC, rjeffman commented on README-group.md
> +  become: true
`become: true` is not needed, please remove it.

2023-03-30 19:51 UTC, rjeffman commented on README-group.md
> +  become: true
`become: true` is not needed, please remove it.

2023-03-30 19:51 UTC, rjeffman commented on README-group.md
> +  become: true
`become: true` is not needed, please remove it.

2023-03-30 19:51 UTC, rjeffman commented on README-group.md
> +  become: true
`become: true` is not needed, please remove it.

2023-03-30 19:52 UTC, rjeffman commented on README-group.md
> +  become: true
`become: true` is not needed, please remove it.

2023-03-30 19:52 UTC, rjeffman commented on playbooks/group/add-groups.yml
> +  become: true
`become: true` is not needed, please remove it.

2023-03-30 19:53 UTC, rjeffman commented on tests/group/test_groups.yml
> +  become: yes
`become: true` is not needed, please remove it.

2023-03-30 19:54 UTC, rjeffman commented on tests/group/test_groups.yml
> +  gather_facts: yes
Please, use only `true` and `false` for boolean values.

2023-03-30 19:54 UTC, rjeffman commented on tests/group/test_groups_absent.yml
> +  become: true
`become: true` is not needed, please remove it.

2023-03-30 19:55 UTC, rjeffman commented on tests/group/test_groups_present.yml
> +  become: true
`become: true` is not needed, please remove it.

2023-03-30 19:55 UTC, rjeffman commented on tests/group/test_groups_present_slice.yml
> +  become: true
`become: true` is not needed, please remove it.

2023-03-30 19:56 UTC, rjeffman requested changes
Please, on all playbooks (example, documentation and tests), use only `true` and `false` for boolean values.

2023-03-31 17:48 UTC, rjeffman approved these changes
LGTM

2023-04-04 09:01 UTC, t-woerner commented on README-group.md
> +  - ipagroup:
This should be a named task.

2023-04-04 09:20 UTC, t-woerner commented on tests/group/test_groups_absent.yml
> +
Please insert this task:

    - name: Initialize groups_names
      ansible.builtin.set_fact:
        groups_names: []

This is needed if several of the groups tests using `groups_names` are executed in a row.

2023-04-04 09:21 UTC, t-woerner commented on tests/group/test_groups_present.yml
> +
Please insert this task:

    - name: Initialize groups_names
      ansible.builtin.set_fact:
        groups_names: []

This is needed if several of the groups tests using `groups_names` are executed in a row.

2023-04-04 09:21 UTC, t-woerner commented on tests/group/test_groups_present_slice.yml
> +
Please insert this task:

    - name: Initialize groups_names
      ansible.builtin.set_fact:
        groups_names: []

This is needed if several of the groups tests using `groups_names` are executed in a row.

2023-04-04 09:28 UTC, t-woerner commented on plugins/modules/ipagroup.py
>      required: true
`name` is not required anymore with this change.

2023-04-04 09:39 UTC, t-woerner commented
@dkarpele Please fix the latest findings, then we are able to merge the PR.

2023-04-04 11:19 UTC, t-woerner approved these changes
LGTM

2023-04-04 11:35 UTC, merged