Create action group in collection for module_defaults
freeipa/ansible-freeipa pull request #1080
Opened 2023-04-18 11:43 UTC by t-woerner

**New utils/facts.py: Provide facts about the repo like role and module lists**

The list of modules and roles is needed in several scripts now,
therefore it makes sense to have one place for this.

Here are the current variables:

    BASE_DIR:           Base directory of the repo
    ROLES:              List of roles in the roles folder
    MANAGEMENT_MODULES: List of management modules in the plugins/modules
                        folder
    ROLES_MODULES:      List of modules in the roles/*/library folders
    ALL_MODULES:        List of all modules, the management and the roles
                        modules

All lists are sorted.

**utils/galaxyfy.py: Handle module_defaults, match roles and modules**

The section module_defaults was not handled by utils/galaxyfy.py, also
there was no verification that only roles and modules provided by
ansible-freeipa are matched for prepending the collection prefix.

**utils/build-galaxy-release.sh: Create module action group**

The module action group `<collection-prefix>.modules` is created
automatically while building the galaxy release.

The action group can be used for module_defaults in this way:

      module_defauls:
        group/<collection-prefix>.modules:
          ipaadmin_password: SomeADMINpassword

Example:

      module_defaults:
        group/freeipa.ansible_freeipa.modules:
          ipaadmin_password: SomeADMINpassword
          ipaapi_context: "{{ ipa_context | default(omit) }}"
      collections:
      - freeipa.ansible_freeipa

2023-04-19 18:52 UTC, rjeffman requested changes
IMO, the copyright notice should be fixed before merge.

Otherwise, changes look good to me.

2023-04-20 08:05 UTC, t-woerner commented on utils/galaxyfy.py
> +# Copyright (C) 2019,2020,2023 Red Hat
Fixed

2023-04-20 11:23 UTC, rjeffman approved these changes
LGTM

2023-04-20 13:03 UTC, merged

2023-04-20 17:56 UTC, lessfoobar commented
thanks