ipaserver: Fix deployment after Bronze-bit fix
freeipa/ansible-freeipa pull request #1206
Opened 2024-02-06 01:52 UTC by rjeffman

As FreeIPA now requires MS-PAC to be set in ipaKrbAuthzData to trigger PAC generation, there's a timing issue that causes API malfunction which is long enough to cause the client part insallation to fail.

By restarting KDC after DS password is set, we force cached values to be refreshed, allowing the API to work correctly.

Fixes #1200

2024-02-06 11:25 UTC, varunmylaraiah approved these changes
Thanks for the quick fix. I've tested it successfully across 8.10 downstream test suites, including Server, replica, and client deployments. Everything is working as expected.

2024-02-07 02:39 UTC, varunmylaraiah requested changes
Unfortunately, this patch is failing on the 9.4 replica, specifically on the test case named "rsn_enabled_on_master_and_replica."

2024-02-07 13:57 UTC, t-woerner commented on roles/ipaserver/library/ipaserver_set_ds_password.py
> +    fstore = sysrestore.FileStore(paths.SYSRESTORE)
This is already done in line 204.

2024-02-07 15:17 UTC, rjeffman commented on roles/ipaserver/library/ipaserver_set_ds_password.py
> +    fstore = sysrestore.FileStore(paths.SYSRESTORE)
Fixed.

2024-02-07 15:50 UTC, varunmylaraiah commented
> Unfortunately, this patch is failing on the 9.4 replica, specifically on the test case named "rsn_enabled_on_master_and_replica."

Sorry, I tested with the wrong metadata. Everything is working as expected in 9.4 as well

2024-02-07 15:51 UTC, varunmylaraiah approved these changes

2024-02-07 15:53 UTC, t-woerner approved these changes
LGTM

2024-02-07 15:54 UTC, merged