New inventory plugin
freeipa/ansible-freeipa pull request #1231
Opened 2024-05-03 15:43 UTC by t-woerner

The inventory plugin compiles a dynamic inventory from IPA domain, filters servers by role(s).

Usage:

Create yml file, for example `freeipa.yml`:

    ---
    plugin: freeipa
    server: server.ipa.local
    ipaadmin_password: SomeADMINpassword

Get compiled inventory:

    ansible-inventory -i freeipa.yml --graph

2024-05-03 17:39 UTC, varunmylaraiah commented on README-inventory-plugin-freeipa.md
> +address: server.ipa.local
"address" variable is used instead of "server."

2024-05-03 17:41 UTC, varunmylaraiah requested changes
@t-woerner 
Thank you for the pull request.
In the example playbook, the "address" variable is used instead of "server." Kindly update it accordingly.

2024-05-10 11:56 UTC, varunmylaraiah approved these changes
changes LGTM

2024-05-13 14:28 UTC, rjeffman requested changes

2024-05-13 14:28 UTC, rjeffman commented on README.md
> +
The last line is related to modules and not the inventory plugin.

Either this section is moved after it, or a new section "Writing new modules" is added here.

2024-05-14 11:59 UTC, rjeffman approved these changes
LGTM.

2024-05-14 12:00 UTC, merged