New privilege management module
freeipa/ansible-freeipa pull request #357
Opened 2020-08-20 22:14 UTC by rjeffman

There is a new privilege management module placed in the plugins folder:

    plugins/modules/ipaprivilege.py

The privilege module allows to ensure presence or absence of privilege
and manage privilege permission memebers.

Here is the documentation for the module:

    README-privilege.md

New example playbooks have been added:

    playbooks/privilege/privilege-absent.yml
    playbooks/privilege/privilege-member-absent.yml
    playbooks/privilege/privilege-member-present.yml
    playbooks/privilege/privilege-present.yml

New tests for the module:

    tests/privilege/test_privilege.yml

2020-08-24 07:54 UTC, varunmylaraiah reviewed
Test coverage looks good to me.

2020-09-03 10:46 UTC, t-woerner requested changes

2020-09-03 10:46 UTC, t-woerner commented on README-privilege.md
> +`state` | The state to ensure. It can be one of `present`, `absent`, default: `present`. | no
This is lacking `renamed`

2020-09-03 19:25 UTC, rjeffman commented on README-privilege.md
> +`state` | The state to ensure. It can be one of `present`, `absent`, default: `present`. | no
Fixed.

2020-09-04 14:23 UTC, t-woerner approved these changes

2020-09-04 15:15 UTC, merged