New backup role
freeipa/ansible-freeipa pull request #422
Opened 2020-10-22 11:14 UTC by t-woerner

There is a new backup role in the roles folder:

   roles/ipabackup

This role allows to backup and IPA server, to copy a backup from the server
to the controller and to remove a backup from the server.

Here is the documentation for the role:

    roles/ipabackup/README.md

New example playbooks have been added:

    playbooks/backup-server.yml
    playbooks/copy-backup-from-server.yml
    playbooks/remove-backup-from-server.yml

2020-10-28 20:06 UTC, rjeffman requested changes
It seems to be working fine, but there are two issues with documentation.

2020-10-29 10:26 UTC, amore17 commented
When empty input is given for `ipabackup_name` 
It should fail with more clear error.

`fatal: [master.ipa.test]: FAILED! => {"msg": "The conditional check 'ipabackup_item is not defined or ipabackup_item | length < 1 or (ipabackup_item.find(\"ipa-full-\") == -1 and ipabackup_item.find(\"ipa-data-\") == -1)' failed. The error was: An unhandled exception occurred while templating '{{ main_item | basename }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unexpected templating type error occurred on ({{ main_item | basename }}): expected str, bytes or os.PathLike object, not NoneType\n\nThe error appears to be in '/root/ansible-freeipa/roles/ipabackup/tasks/copy_backup_from_server.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Fail on invalid ipabackup_item\n  ^ here\n"}
`

2020-10-29 10:28 UTC, amore17 commented
Can we copy and remove multiple backup ?
As there we can only perform for single and for all backup.

2020-10-29 15:02 UTC, t-woerner commented on roles/ipabackup/README.md
> +ipabackup_name | Only to remove server local backup with `state: absent` or to copy server local backup to the controller with `state: copied`, string | no
Fixed

2020-10-29 15:05 UTC, t-woerner commented
I fixed empty `ipabackup_name` and added support for a list of backups in ipabackup_name for `action: copied` and `action: absent`.

2020-10-30 10:37 UTC, amore17 commented
Also required fix for empty `ipabackup_log_file`

2020-11-06 14:24 UTC, t-woerner commented
There is a new PR with a combined backup and restore role: https://github.com/freeipa/ansible-freeipa/pull/430

2020-11-06 14:24 UTC, closed without merging