ipadnszone: Accept localhost and localnet in allow_query.
freeipa/ansible-freeipa pull request #632
Opened 2021-09-03 21:44 UTC by zpericic

Bind allows localhost and localnet in allow query so we should accept it.

2021-09-04 03:04 UTC, rjeffman commented
As FreeIPA manages users and hosts in a central location, what is the use case to have its integrated DNS nameserver to only respond to local queries?

2021-09-04 15:18 UTC, zpericic commented
> As FreeIPA manages users and hosts in a central location, what is the use case to have its integrated DNS nameserver to only respond to local queries for a specific zone?

It is accepted by bind, bind-dyndb-ldap and IPA so why wouldn't we allow it... 

I use it in conjunction with other ACIs eg. "localhost; 10/8;". 

There is many use cases when you want to be able resolve domain on DNS machine. It's not disallowed to use other software on IPA server. It's recommended not to use any network service which could compromise IPA, but it's not mandatory. and you may want to resolve from some local software.

Some examples are null client for mail, remote logging, monitoring...

2021-09-05 01:19 UTC, rjeffman requested changes

2021-09-05 01:19 UTC, rjeffman commented on plugins/modules/ipadnszone.py
>                  ip == "none"
Please, change this to `ip in ["any", "localhost", "localnets", "none"]`.

2021-09-06 13:51 UTC, rjeffman approved these changes
LGTM.

2021-09-06 13:51 UTC, merged