ipavault: Fix documentation sections and agument spec
freeipa/ansible-freeipa pull request #958
Opened 2022-09-30 16:44 UTC by t-woerner

ansible-test with ansible-2.14 is adding a lot of new tests to ensure that the documentation section and the agument spec is complete. Needed changes:

DOCUMENTATION section

- `type: str` needs to be set for string parameters
- `type: bool` needs to be set for bool parameters

- `type: list` needs to be set for list parameters
- `elements: str` needs to be given for list of string parameters
- `type: string` is not valid and needs to be replaced by `type: str`
- `required` tags need to be fixed according to the `argument_spec`
- `aliases` tag needs to match `argument_spec`
- `author` needs to be given with the github user also: `Name (@user)`
- `choices` needs to match `argument_spec`
- all parameters need to be defined

RETURN section

- `contains` needs to be used instead of `options` for dicts
- `type: string` is not valid and needs to be replaced by `type: str`

argument_spec

- `elements="str"` needs to be added to all list of string parameters
- `default=.*` needs to be dropped if `required=True` is also given

The `copyright` date is extended with `-2022`.

2022-10-04 10:40 UTC, varunmylaraiah requested changes

2022-10-04 10:40 UTC, varunmylaraiah commented on plugins/modules/ipavault.py
> +    aliases: ["ipavaultpublickey", "public_key", "new_public_key"]
We need to update "[README-vault.md](https://github.com/freeipa/ansible-freeipa/blob/master/README-vault.md)" for new_public_key.

2022-10-04 10:40 UTC, varunmylaraiah commented on plugins/modules/ipavault.py
> +    aliases: ["public_key_file", "new_public_key_file"]
same as above for "new_public_key_file"

2022-10-21 17:52 UTC, rjeffman approved these changes
LGTM.

2022-10-26 06:05 UTC, varunmylaraiah approved these changes

2022-10-26 11:41 UTC, merged