ipaconfig: Do not require enable_sid for add_sids or netbios_name
freeipa/ansible-freeipa pull request #961
Opened 2022-10-13 16:33 UTC by rjeffman

Current behavior of ipaconfig mimics FreeIPA CLI and requires that
'enable_sid' is set to True every time add_sids or netbios_name are
used. It is sufficient that SID generation is enabled to use add_sids
and netbios_name, but the IPA API requires 'enable_sid' so that the
operations are executed.

This patch allows ansible-freeipa plugin ipaconfig to run 'add_sids' or
set 'netbios_name without requiring 'enable_sid' to be set on the
playbook.

If SID generation is enabled, 'add_sids' and 'netbios_name' can be used
without 'enable_sid: yes'. If SID generation is not enabled, an error
message will be raised if 'enable_sid: yes' is not used.

Depends on PR #921 being merged (due to commit 3c7bd565ecfbca802110f85ef8ae679c053d8bdb).

Fixes [RHBZ#2134550](https://bugzilla.redhat.com/show_bug.cgi?id=2134505)

2022-10-17 18:03 UTC, varunmylaraiah requested changes
Rafael, the below test, is failing

```
---
- name: Playbook to ensure not able to update netbios_name with smallcase.
  hosts: ipaserver

  tasks:
  - ipaconfig:
      ipaadmin_password: <xxxxxxxx>
      enable_sid: yes
      netbios_name: newtestnetbios


 [ PLAY [Playbook to ensure not able to update netbios_name with smallcase.] ******
 [
 [ TASK [Gathering Facts] *********************************************************
 [ task path: /root/config_module.yml:2
 ok: [master.ipadomain.test]
 META: ran handlers

 TASK [ipaconfig] ***************************************************************
 task path: /root/config_module.yml:6
ok: [master.ipadomain.test] => {"changed": false, "config": {}}
META: ran handlers
META: ran handlers
2022-10-17T17:28:40+0000 [
PLAY RECAP *********************************************************************
master.ipadomain.test      : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

Expected error: "only uppercase ASCII letters, digits and dashes are allowed"

2022-10-17 18:29 UTC, rjeffman commented
This is interesting, this code was available before, did pass all tests.

Nonetheless, this was a bug in the code and is fixed by the latest update.

2022-10-18 07:08 UTC, varunmylaraiah approved these changes
Thanks, @rjeffman, the above issue is resolved. The rest of the changes are LGTM.

2022-10-18 09:17 UTC, t-woerner commented
An old version of #921 is part of this PR.

2022-10-18 14:18 UTC, t-woerner approved these changes
LGTM

2022-10-18 14:28 UTC, merged